# For full config options, check the docs:
#    docs.serverless.com

service: iagdsendmail
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  environment:
    SECRET: ${ssm:secret}
    GIN_MODE: release

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  appName: IAGD-Sendmail
  stage: ${opt:stage, self:provider.stage}

functions:
  SendMail:
    handler: bin/sendmail
    events:
      - http:
          path: sendmail
          method: post

