AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Description:
  An example RESTful service
Resources:
  EventsCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./bin/subscriptions_list.zip
      Runtime: go1.x
      Timeout: 30
      Environment:
        Variables:
          DATABASE_USER:
          DATABASE_PASSWORD:
          DATABASE_HOST:
          DATABASE_NAME:
          AUTHENTICATION_TOKEN:
      Events:
        GetRates:
          Type: Api
          Properties:
            Path: /subscriptions
            Method: get