
# For full storage options, check the docs:
#    docs.serverless.com

service: iabackup
# app and org for use with dashboard.serverless.com TODO: Look into this?
app: iabackup
org: marius00

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  vpc:
  environment:
    LAMBDA_HOST: ${ssm:lambda_host}
    ALLOWED_ORIGIN: ${ssm:allowed_origin}


package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  appName: iabackup
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: iabackup-bucket # Must be globally unique
    distributionFolder: client/build

functions:
  DeleteAccount:
    handler: bin/delete
    events:
      - http:
          path: /delete
          method: delete
  DownloadItems:
    handler: bin/download
    events:
      - http:
          path: /download
          method: get
  AzureMigration:
    handler: bin/migrate
    events:
      - http:
          path: /migrate
          method: post
  RemoveItems:
    handler: bin/remove
    events:
      - http:
          path: /remove
          method: post
  Auth:
    handler: bin/auth
    events:
      - http:
          path: /auth
          method: post
  Login:
    handler: bin/login
    events:
      - http:
          path: /login
          method: get
  LoginCheck:
    handler: bin/logincheck
    events:
      - http:
          path: /logincheck
          method: get
  UploadItems:
    handler: bin/upload
    events:
    - http:
        path: /upload
        method: post

# you can add CloudFormation resource templates here
plugins:
  - serverless-finch
resources:
  - ${file(resources/s3-bucket.yml)}
