service: iabackup

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 128
  environment:
    DATABASE_USER: ${ssm:/gd/ia/backup/config/db/user}
    DATABASE_PASSWORD: ${ssm:/gd/ia/backup/config/db/password}
    DATABASE_HOST: ${ssm:/gd/ia/backup/config/db/hostname}
    DATABASE_NAME: ${ssm:/gd/ia/backup/config/db/database}
    ALLOWED_ORIGIN: ${ssm:/gd/ia/backup/config/allowed_origin}
    GO_API_HOST: ${ssm:/gd/ia/backup/config/api_host}
    REGION: ${ssm:/gd/ia/backup/config/region}
    BUCKETNAME: ${ssm:/gd/ia/backup/config/backupbucket}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  appName: iabackup
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: iagd.evilsoft.net # Must be globally unique
    distributionFolder: client/build

functions:
  DownloadBuddyItems:
    handler: bin/buddyitems
    events:
      - http:
          path: /buddyitems
          method: get
  SearchOnlineItems:
    handler: bin/search
    events:
      - http:
          path: /search
          method: get
  DeleteAccount:
    handler: bin/delete
    events:
      - http:
          path: /delete
          method: delete
  DownloadItems:
    handler: bin/download
    events:
      - http:
          path: /download
          method: get
  GetBuddyId:
    handler: bin/getbuddyid
    events:
      - http:
          path: /buddyId
          method: get
  AzureMigration:
    handler: bin/migrate
    events:
      - http:
          path: /migrate
          method: get
  RemoveItems:
    handler: bin/remove
    events:
      - http:
          path: /remove
          method: post
  Auth:
    handler: bin/auth
    events:
      - http:
          path: /auth
          method: post
          cors: true
  Login:
    handler: bin/login
    events:
      - http:
          path: /login
          method: get
          cors: true
  LoginCheck:
    handler: bin/logincheck
    events:
      - http:
          path: /logincheck
          method: get
  Logout:
    handler: bin/logout
    events:
      - http:
          path: /logout
          method: post
  UploadItems:
    handler: bin/upload
    events:
    - http:
        path: /upload
        method: post
  CharacterBackup:
    handler: bin/character
    events:
    - http:
        path: /character/upload
        method: post
    - http:
        path: /character/download
        method: get
    - http:
        path: /character
        method: get
  Maintenance:
    handler: bin/maintenance
    events:
      - schedule: cron(0 6 ? * 1 *) # Every monday, 06:00 - Completely arbitrary time

# you can add CloudFormation resource templates here
plugins:
  - serverless-finch
resources:
  - ${file(resources/s3-bucket.yml)}
