
# For full storage options, check the docs:
#    docs.serverless.com

service: iabackup
# app and org for use with dashboard.serverless.com TODO: Look into this?
# app: iabackup
# org: marius00

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 256 # 128?
  environment:
    DATABASE_USER: ${ssm:/gd/ia/backup/config/db/user}
    DATABASE_PASSWORD: ${ssm:/gd/ia/backup/config/db/password}
    DATABASE_HOST: ${ssm:/gd/ia/backup/config/db/hostname}
    DATABASE_NAME: ${ssm:/gd/ia/backup/config/db/database}
    ALLOWED_ORIGIN: ${ssm:/gd/ia/backup/config/allowed_origin}


package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  appName: iabackup
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: iagd.evilsoft.net # Must be globally unique
    distributionFolder: client/build

functions:
  DeleteAccount:
    handler: bin/delete
    events:
      - http:
          path: /delete
          method: delete
  DownloadItems:
    handler: bin/download
    events:
      - http:
          path: /download
          method: get
  AzureMigration:
    handler: bin/migrate
    events:
      - http:
          path: /migrate
          method: get
  RemoveItems:
    handler: bin/remove
    events:
      - http:
          path: /remove
          method: post
  Auth:
    handler: bin/auth
    events:
      - http:
          path: /auth
          method: post
          cors: true
  Login:
    handler: bin/login
    events:
      - http:
          path: /login
          method: get
          cors: true
  LoginCheck:
    handler: bin/logincheck
    events:
      - http:
          path: /logincheck
          method: get
  Logout:
    handler: bin/logout
    events:
      - http:
          path: /logout
          method: post
  UploadItems:
    handler: bin/upload
    events:
    - http:
        path: /upload
        method: post
  Maintenance:
    handler: bin/maintenance
    events:
      - schedule: cron(0 6 * * 1 *) # Every monday, 06:00 - Completely arbitrary time

# you can add CloudFormation resource templates here
plugins:
  - serverless-finch
resources:
  - ${file(resources/s3-bucket.yml)}
