
# For full storage options, check the docs:
#    docs.serverless.com

service: iabackup
# app and org for use with dashboard.serverless.com TODO: Look into this?
#app: your-app-name
#org: your-org-name

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0b126c5c
  environment:
    LAMBDA_HOST: ${ssm:lambda_host}
    ALLOWED_ORIGIN: ${ssm:allowed_origin}


package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom:
  appName: iabackup
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: iabackup-bucket # Must be globally unique
    distributionFolder: client/build

functions:
  ListPartitions:
    handler: bin/partitions
    events:
      - http:
          path: /partitions
          method: get
  UploadItems:
    handler: bin/upload
    events:
    - http:
        path: /upload
        method: post
  DownloadItems:
    handler: bin/download
    events:
    - http:
        path: /download
        method: get
  RemoveItems:
    handler: bin/remove
    events:
    - http:
        path: /remove
        method: post
  LoginCheck:
    handler: bin/logincheck
    events:
    - http:
        path: /logincheck
        method: get
  AzureMigration:
    handler: bin/migrate
    events:
    - http:
        path: /migrate
        method: post

# you can add CloudFormation resource templates here
plugins:
  - serverless-finch
resources:
  - ${file(resources/s3-bucket.yml)}
